import { Router } from 'express';
import { requireAdmin, requireAuth } from '../../middleware/auth';
import type { UserRepository } from '../users/user.repository';
import { makeAdminController } from './admin.controller';
import { AdminService } from './admin.service';
import type { AdminStore } from './admin.store';
import { LocalFileStorage, type FileStorage } from '../../services/file-storage';

export function makeAdminRoutes(users: UserRepository, store: AdminStore, storage: FileStorage = new LocalFileStorage()): Router {
  const router = Router();
  const controller = makeAdminController(new AdminService(users, store, storage));
  router.use(requireAuth(users), requireAdmin());
  router.get('/admin/dashboard', controller.dashboard);
  router.get('/admin/users', controller.listUsers);
  router.get('/admin/users/:id', controller.getUser);
  router.post('/admin/users/:id/suspend', controller.suspendUser);
  router.post('/admin/users/:id/reactivate', controller.reactivateUser);
  router.get('/admin/customers', controller.listCustomers);
  router.get('/admin/customers/:id', controller.getCustomer);
  router.get('/admin/professionals', controller.listProfessionals);
  router.get('/admin/professionals/:id', controller.getProfessional);
  router.get('/admin/businesses', controller.listBusinesses);
  router.get('/admin/businesses/:id', controller.getBusiness);
  router.get('/admin/technicians', controller.listTechnicians);
  router.get('/admin/technicians/:id', controller.getTechnician);
  router.get('/admin/services/categories', controller.listServiceCategories);
  router.get('/admin/services', controller.listServices);
  router.get('/admin/services/:id', controller.getService);
  router.post('/admin/services', controller.createService);
  router.patch('/admin/services/:id', controller.updateService);
  router.post('/admin/services/:id/activate', controller.activateService);
  router.post('/admin/services/:id/deactivate', controller.deactivateService);
  router.get('/admin/jobs', controller.listJobs);
  router.get('/admin/jobs/:id', controller.getJob);
  router.get('/admin/verifications', controller.listVerifications);
  router.get('/admin/verifications/:id', controller.getVerification);
  router.get('/admin/verifications/:id/document', controller.getVerificationDocument);
  router.post('/admin/verifications/:id/approve', controller.approveVerification);
  router.post('/admin/verifications/:id/reject', controller.rejectVerification);
  router.post('/admin/verifications/:id/request-info', controller.requestVerificationInfo);
  router.get('/admin/certificates', controller.listCertificates);
  router.get('/admin/certificates/:id', controller.getCertificate);
  router.get('/admin/certificates/:id/document', controller.getCertificateDocument);
  router.post('/admin/certificates/:id/approve', controller.approveCertificate);
  router.post('/admin/certificates/:id/reject', controller.rejectCertificate);
  router.post('/admin/certificates/:id/request-info', controller.requestCertificateInfo);
  router.get('/admin/reviews', controller.listReviews);
  router.get('/admin/reviews/:id', controller.getReview);
  router.get('/admin/reports', controller.listReports);
  router.get('/admin/reports/:id', controller.getReport);
  router.patch('/admin/reports/:id/status', controller.updateReport);
  router.get('/admin/disputes', controller.listDisputes);
  router.get('/admin/disputes/:id', controller.getDispute);
  router.patch('/admin/disputes/:id', controller.updateDispute);
  router.get('/admin/audit-logs', controller.listAuditLogs);
  router.get('/admin/audit-logs/:id', controller.getAuditLog);
  return router;
}
