import type { AdminDocumentReference, AdminStore } from './admin.store';
import { AdminStoreError } from './admin.store';
import type { UserRepository, UserStatus } from '../users/user.repository';
import type {
  AdminAuditFilters,
  AdminAuditLogDto,
  AdminBusinessDto,
  AdminBusinessDetailDto,
  AdminBusinessFilters,
  AdminCertificateDto,
  AdminCertificateFilters,
  AdminCustomerDto,
  AdminCustomerDetailDto,
  AdminDashboardDto,
  AdminDisputeDto,
  AdminDisputeFilters,
  AdminJobDto,
  AdminJobDetailDto,
  AdminJobFilters,
  AdminList,
  AdminProviderDto,
  AdminProfessionalDetailDto,
  AdminProviderFilters,
  AdminReportDto,
  AdminReportFilters,
  AdminReviewDto,
  AdminReviewFilters,
  AdminServiceCategoryDto,
  AdminServiceDto,
  AdminServiceFilters,
  AdminTechnicianDto,
  AdminTechnicianDetailDto,
  AdminTechnicianFilters,
  AdminVerificationDto,
  AdminVerificationFilters,
  CertificateDecisionInput,
  DisputeUpdateInput,
  ReportStatusInput,
  ServiceMutationInput,
  VerificationDecisionInput,
} from './admin.types';

const now = (): string => new Date().toISOString();
const startOfDay = (value: string): string => value.length === 10 ? `${value}T00:00:00.000Z` : value;
const endOfDay = (value: string): string => value.length === 10 ? `${value}T23:59:59.999Z` : value;
const textMatch = (values: Array<string | null>, search: string | null): boolean => !search || values.join(' ').toLowerCase().includes(search.toLowerCase());
const page = <T>(items: T[], p: { page: number; pageSize: number }): AdminList<T> => ({ items: items.slice((p.page - 1) * p.pageSize, p.page * p.pageSize), total: items.length, page: p.page, pageSize: p.pageSize });

export interface MemoryAdminDocumentSeed {
  storageKey: string;
  mimeType: string;
  filename: string;
}

export class MemoryAdminStore implements AdminStore {
  constructor(private readonly users?: UserRepository, private readonly documents: Record<string, MemoryAdminDocumentSeed> = {}) {}
  private serviceSeq = 20;
  private auditSeq = 1;
  private readonly customers: AdminCustomerDto[] = [
    { id: '1', userId: '101', businessId: null, firstName: 'Naledi', lastName: 'Dlamini', displayName: 'Naledi Dlamini', email: 'naledi@example.co.za', phone: '+27825550101', preferredContact: 'EMAIL', createdAt: '2026-09-01T08:00:00.000Z', updatedAt: '2026-09-01T08:00:00.000Z' },
    { id: '2', userId: '102', businessId: '1', firstName: 'Thabo', lastName: 'Mokoena', displayName: 'Thabo Mokoena', email: 'thabo@example.co.za', phone: null, preferredContact: 'PHONE', createdAt: '2026-09-02T08:00:00.000Z', updatedAt: '2026-09-02T08:00:00.000Z' },
  ];
  private readonly professionals: AdminProviderDto[] = [
    { id: '1', userId: '201', name: 'Sipho Ndlovu', bio: 'PIRB-registered plumber', experienceYears: 9, verificationStatus: 'VERIFIED', ratingAvg: 4.8, ratingCount: 64, isActive: true, city: 'Johannesburg', province: 'Gauteng', serviceCount: 3, portfolioCount: 1, certificateCount: 1, createdAt: '2026-08-01T08:00:00.000Z', updatedAt: '2026-09-20T08:00:00.000Z' },
    { id: '2', userId: '202', name: 'Maria Santos', bio: 'Painter', experienceYears: 6, verificationStatus: 'PENDING', ratingAvg: 0, ratingCount: 0, isActive: true, city: 'Durban', province: 'KwaZulu-Natal', serviceCount: 2, portfolioCount: 0, certificateCount: 0, createdAt: '2026-08-02T08:00:00.000Z', updatedAt: '2026-09-21T08:00:00.000Z' },
  ];
  private readonly businesses: AdminBusinessDto[] = [
    { id: '1', ownerUserId: '301', name: 'Ubuntu Plumbing Co.', description: 'Family-run plumbing team', email: 'hello@ubuntu.example', phone: '+27825550103', addressLine1: '1 Main Road', city: 'Johannesburg', province: 'Gauteng', postalCode: '2196', verificationStatus: 'VERIFIED', ratingAvg: 4.6, ratingCount: 48, isActive: true, technicianCount: 1, serviceCount: 3, createdAt: '2026-08-01T08:00:00.000Z', updatedAt: '2026-09-20T08:00:00.000Z' },
    { id: '2', ownerUserId: '302', name: 'Cape Spark Electrical', description: 'Electrical team', email: null, phone: null, addressLine1: null, city: 'Cape Town', province: 'Western Cape', postalCode: null, verificationStatus: 'PENDING', ratingAvg: 0, ratingCount: 0, isActive: true, technicianCount: 0, serviceCount: 2, createdAt: '2026-08-02T08:00:00.000Z', updatedAt: '2026-09-21T08:00:00.000Z' },
  ];
  private readonly technicians: AdminTechnicianDto[] = [{ id: '1', businessId: '1', userId: '303', displayName: 'Lerato Maseko', email: 'lerato@ubuntu.example', phone: '+27825550104', isActive: true, createdAt: '2026-08-03T08:00:00.000Z', updatedAt: '2026-09-20T08:00:00.000Z' }];
  private readonly categories: AdminServiceCategoryDto[] = [
    { id: '1', name: 'Plumbing', slug: 'plumbing', description: 'Water and drainage work', isActive: true, sortOrder: 1 },
    { id: '2', name: 'Electrical', slug: 'electrical', description: 'Wiring and lighting', isActive: true, sortOrder: 2 },
    { id: '3', name: 'Painting', slug: 'painting', description: 'Interior and exterior painting', isActive: true, sortOrder: 3 },
  ];
  private readonly services: AdminServiceDto[] = [
    { id: '1', categoryId: '1', categoryName: 'Plumbing', categorySlug: 'plumbing', name: 'Leak Repair', slug: 'leak-repair', description: 'Fix leaks', isActive: true, sortOrder: 1, createdAt: '2026-08-01T08:00:00.000Z', updatedAt: '2026-09-01T08:00:00.000Z' },
    { id: '2', categoryId: '2', categoryName: 'Electrical', categorySlug: 'electrical', name: 'DB Board Repairs', slug: 'db-board-repairs', description: 'Board repairs', isActive: true, sortOrder: 1, createdAt: '2026-08-01T08:00:00.000Z', updatedAt: '2026-09-01T08:00:00.000Z' },
    { id: '3', categoryId: '3', categoryName: 'Painting', categorySlug: 'painting', name: 'Interior Painting', slug: 'interior-painting', description: 'Interior painting', isActive: false, sortOrder: 1, createdAt: '2026-08-01T08:00:00.000Z', updatedAt: '2026-09-01T08:00:00.000Z' },
  ];
  private readonly jobs: AdminJobDto[] = [
    { id: '1', reference: 'FL-2026-000001', source: 'MARKETPLACE', status: 'REQUESTED', customerId: '1', professionalId: '1', businessId: null, serviceId: '1', title: null, description: 'Repair a leaking tap', city: 'Johannesburg', province: 'Gauteng', scheduledAt: null, agreedAmount: null, currency: 'ZAR', createdAt: '2026-09-20T08:00:00.000Z', updatedAt: '2026-09-20T08:00:00.000Z' },
    { id: '2', reference: 'FL-2026-000002', source: 'INTERNAL', status: 'IN_PROGRESS', customerId: '2', professionalId: null, businessId: '1', serviceId: '1', title: 'Emergency leak', description: 'Internal plumbing work', city: 'Johannesburg', province: 'Gauteng', scheduledAt: '2026-09-22T09:00:00.000Z', agreedAmount: 450, currency: 'ZAR', createdAt: '2026-09-21T08:00:00.000Z', updatedAt: '2026-09-22T08:00:00.000Z' },
  ];
  private readonly verifications: AdminVerificationDto[] = [
    { id: '1', userId: '202', userEmail: 'maria@example.co.za', type: 'IDENTITY', status: 'PENDING', reviewedBy: null, reviewedAt: null, reviewNotes: null, createdAt: '2026-09-21T08:00:00.000Z', updatedAt: '2026-09-21T08:00:00.000Z' },
    { id: '2', userId: '302', userEmail: 'owner@capespark.example', type: 'BUSINESS', status: 'PENDING', reviewedBy: null, reviewedAt: null, reviewNotes: null, createdAt: '2026-09-21T08:00:00.000Z', updatedAt: '2026-09-21T08:00:00.000Z' },
    { id: '3', userId: '201', userEmail: 'sipho@example.co.za', type: 'CERTIFICATE', status: 'PENDING', reviewedBy: null, reviewedAt: null, reviewNotes: null, createdAt: '2026-09-21T08:00:00.000Z', updatedAt: '2026-09-21T08:00:00.000Z' },
  ];
  private readonly identity = new Map<string, 'PENDING' | 'APPROVED' | 'REJECTED' | 'NEEDS_INFO'>([['1', 'PENDING']]);
  private readonly certificateHistory = new Map<string, Array<'APPROVED' | 'REJECTED' | 'NEEDS_INFO'>>([]);
  private readonly certificates: AdminCertificateDto[] = [{ id: '1', professionalId: '1', businessId: null, ownerType: 'PROFESSIONAL', title: 'PIRB Registration', issuingOrganisation: 'PIRB', issueDate: '2023-03-14', expiryDate: '2027-03-13', verificationStatus: 'PENDING', reviewedBy: null, reviewedAt: null, reviewNotes: null, createdAt: '2026-09-19T08:00:00.000Z', updatedAt: '2026-09-19T08:00:00.000Z' }];
  private readonly reviews: AdminReviewDto[] = [{ id: '1', jobId: '2', customerId: '2', professionalId: null, businessId: '1', customerName: 'Thabo Mokoena', providerName: 'Ubuntu Plumbing Co.', rating: 5, comment: 'Excellent work', isVisible: true, createdAt: '2026-09-22T08:00:00.000Z', updatedAt: '2026-09-22T08:00:00.000Z' }, { id: '2', jobId: '1', customerId: '1', professionalId: '1', businessId: null, customerName: 'Naledi Dlamini', providerName: 'Sipho Ndlovu', rating: 4, comment: 'Quick professional', isVisible: true, createdAt: '2026-09-21T08:00:00.000Z', updatedAt: '2026-09-21T08:00:00.000Z' }];
  private readonly reports: AdminReportDto[] = [{ id: '1', reporterId: '101', reportType: 'PROVIDER', entityType: 'BUSINESS', entityId: '1', reason: 'Profile concern', description: 'Please review', status: 'OPEN', resolvedBy: null, resolvedAt: null, createdAt: '2026-09-20T08:00:00.000Z', updatedAt: '2026-09-20T08:00:00.000Z' }];
  private readonly disputes: AdminDisputeDto[] = [{ id: '1', jobId: '2', openedBy: '101', reason: 'Work quality', description: 'Needs review', status: 'OPEN', resolution: null, resolvedBy: null, resolvedAt: null, createdAt: '2026-09-21T08:00:00.000Z', updatedAt: '2026-09-21T08:00:00.000Z' }];
  private readonly audits: AdminAuditLogDto[] = [];
  private failNextAudit = false;

  failNextAuditOnce(): void { this.failNextAudit = true; }
  seedDocument(key: string, document: MemoryAdminDocumentSeed): void { this.documents[key] = document; }
  async getVerificationDocument(id: string): Promise<AdminDocumentReference | null> { const row = this.verifications.find((x) => x.id === id && x.type === 'IDENTITY'); return row && this.documents[`verification:${id}`] ? { ...this.documents[`verification:${id}`] } : null; }
  async getCertificateDocument(id: string): Promise<AdminDocumentReference | null> { const document = this.documents[`certificate:${id}`]; return document ? { ...document } : null; }
  private writeAudit(action: string, entityType: string, entityId: string, actorId: string): void { if (this.failNextAudit) { this.failNextAudit = false; throw new AdminStoreError('INTERNAL', 'Injected audit failure.'); } this.audits.push({ id: String(this.auditSeq++), actorId, actorEmail: null, action, entityType, entityId, metadata: {}, ipAddress: null, createdAt: now() }); }

  async setUserStatus(id: string, expectedStatus: UserStatus, nextStatus: UserStatus, actorId: string): Promise<boolean> { if (!this.users) throw new AdminStoreError('INTERNAL', 'User store is not configured.'); const user = await this.users.findById(id); if (!user) return false; if (user.status !== expectedStatus) throw new AdminStoreError('CONFLICT', 'User status changed.'); try { await this.users.setStatus(id, nextStatus); this.writeAudit(nextStatus === 'SUSPENDED' ? 'USER_SUSPENDED' : 'USER_REACTIVATED', 'USER', id, actorId); return true; } catch (error) { await this.users.setStatus(id, expectedStatus); throw error; } }
  async dashboard(): Promise<AdminDashboardDto> {
    return { users: { total: 0, active: 0, pending: 0, suspended: 0 }, customers: this.customers.length, professionals: { total: this.professionals.length, verified: this.professionals.filter((x) => x.verificationStatus === 'VERIFIED').length, pending: this.professionals.filter((x) => x.verificationStatus === 'PENDING').length }, businesses: { total: this.businesses.length, verified: this.businesses.filter((x) => x.verificationStatus === 'VERIFIED').length, pending: this.businesses.filter((x) => x.verificationStatus === 'PENDING').length }, technicians: { total: this.technicians.length, active: this.technicians.filter((x) => x.isActive).length }, services: { total: this.services.length, active: this.services.filter((x) => x.isActive).length, inactive: this.services.filter((x) => !x.isActive).length }, jobs: { total: this.jobs.length, open: this.jobs.filter((x) => x.status === 'REQUESTED' || x.status === 'QUOTED' || x.status === 'ACCEPTED' || x.status === 'SCHEDULED').length, inProgress: this.jobs.filter((x) => x.status === 'IN_PROGRESS' || x.status === 'AWAITING_PARTS').length, completed: this.jobs.filter((x) => x.status === 'COMPLETED' || x.status === 'CONFIRMED' || x.status === 'CLOSED').length }, verification: { pending: this.verifications.filter((x) => x.status === 'PENDING').length, needsInfo: this.verifications.filter((x) => x.status === 'NEEDS_INFO').length }, certificates: { pending: this.certificates.filter((x) => x.verificationStatus === 'PENDING').length, needsInfo: this.certificates.filter((x) => x.verificationStatus === 'NEEDS_INFO').length }, reports: { open: this.reports.filter((x) => x.status === 'OPEN').length, inReview: this.reports.filter((x) => x.status === 'IN_REVIEW').length }, disputes: { open: this.disputes.filter((x) => x.status === 'OPEN').length, inReview: this.disputes.filter((x) => x.status === 'IN_REVIEW').length } };
  }
  async listCustomers(filters: { search: string | null; page: number; pageSize: number }) { return page(this.customers.filter((x) => textMatch([x.firstName, x.lastName, x.email, x.phone], filters.search)), filters); }
  async getCustomer(id: string): Promise<AdminCustomerDetailDto | null> { const customer = this.customers.find((x) => x.id === id); if (!customer) return null; const jobs = this.jobs.filter((x) => x.customerId === id).slice(0, 50).map((job) => ({ ...job, providerName: this.providerName(job), serviceName: this.serviceName(job.serviceId) })); const reviews = this.reviews.filter((x) => x.customerId === id).slice(0, 50); return { ...customer, jobs, reviews, summary: { jobCount: this.jobs.filter((x) => x.customerId === id).length, activeJobCount: this.jobs.filter((x) => x.customerId === id && ['REQUESTED', 'QUOTED', 'ACCEPTED', 'SCHEDULED', 'IN_PROGRESS', 'AWAITING_PARTS'].includes(x.status)).length, reviewCount: reviews.length, ratingAvg: reviews.length ? reviews.reduce((sum, review) => sum + review.rating, 0) / reviews.length : 0 } }; }
  private providerName(job: AdminJobDto): string { if (job.professionalId) return this.professionals.find((x) => x.id === job.professionalId)?.name ?? 'Professional'; return this.businesses.find((x) => x.id === job.businessId)?.name ?? 'Business'; }
  private serviceName(id: string | null): string { return id ? this.services.find((x) => x.id === id)?.name ?? 'Service' : 'Service'; }
  async listProfessionals(filters: AdminProviderFilters) { return page(this.professionals.filter((x) => (!filters.status || x.verificationStatus === filters.status) && textMatch([x.name, x.bio, x.city], filters.search)), filters); }
  async getProfessional(id: string): Promise<AdminProfessionalDetailDto | null> { const professional = this.professionals.find((x) => x.id === id); if (!professional) return null; const services = this.services.filter((x) => x.isActive && (id === '1' ? ['1', '2', '3'].includes(x.id) : ['6', '7'].includes(x.id))).slice(0, 50).map((x) => ({ id: x.id, name: x.name, slug: x.slug, categoryId: x.categoryId, categoryName: x.categoryName })); const areas = id === '1' ? [{ areaName: 'Randburg & surrounds', city: 'Johannesburg', province: 'Gauteng' }] : [{ areaName: 'Durban North', city: 'Durban', province: 'KwaZulu-Natal' }]; const portfolio = id === '1' ? [{ id: '1', title: 'Northcliff kitchen leak repair', description: 'Leaking mixer replaced', serviceId: '1', serviceName: 'Leak Repair', isPublished: true, imageCount: 2, createdAt: '2026-09-20T10:00:00.000Z' }] : []; const certificates = this.certificates.filter((x) => x.professionalId === id).slice(0, 50); const reviews = this.reviews.filter((x) => x.professionalId === id).slice(0, 50); return { ...professional, services, serviceAreas: areas, portfolio, certificates, identityVerification: id === '2' ? { id: '1', status: this.identity.get('1') ?? 'PENDING', reviewedAt: null } : null, reviews, summary: { serviceCount: services.length, portfolioCount: portfolio.length, certificateCount: certificates.length, reviewCount: reviews.length, ratingAvg: professional.ratingAvg } }; }
  async listBusinesses(filters: AdminBusinessFilters) { return page(this.businesses.filter((x) => (!filters.status || x.verificationStatus === filters.status) && textMatch([x.name, x.email, x.city, x.province], filters.search)), filters); }
  async getBusiness(id: string): Promise<AdminBusinessDetailDto | null> { const business = this.businesses.find((x) => x.id === id); if (!business) return null; const owner = { id: business.ownerUserId, email: id === '1' ? 'owner@ubuntu.example' : 'owner@capespark.example', phone: null, status: 'ACTIVE' as const, roles: ['BUSINESS_OWNER'], lastLoginAt: null }; const members = [{ userId: business.ownerUserId, role: 'BUSINESS_OWNER' as const, isActive: true, invitedAt: null, joinedAt: business.createdAt }]; const technicians = this.technicians.filter((x) => x.businessId === id).slice(0, 50); const jobs = this.jobs.filter((x) => x.businessId === id).slice(0, 50).map((job) => ({ ...job, customerName: this.customers.find((x) => x.id === job.customerId)?.displayName ?? 'Customer' })); return { ...business, owner, members, technicians, jobs, summary: { memberCount: members.length, technicianCount: technicians.length, jobCount: jobs.length, activeJobCount: jobs.filter((x) => !['COMPLETED', 'CONFIRMED', 'CLOSED', 'CANCELLED'].includes(x.status)).length } }; }
  async listTechnicians(filters: AdminTechnicianFilters) { return page(this.technicians.filter((x) => (!filters.businessId || x.businessId === filters.businessId) && (filters.isActive === null || x.isActive === filters.isActive) && textMatch([x.displayName, x.email, x.phone], filters.search)), filters); }
  async getTechnician(id: string): Promise<AdminTechnicianDetailDto | null> { const technician = this.technicians.find((x) => x.id === id); if (!technician) return null; const business = this.businesses.find((x) => x.id === technician.businessId); if (!business) return null; const jobs = this.jobs.filter((x) => x.businessId === technician.businessId && x.id === '2').slice(0, 50).map((job) => ({ ...job, customerName: this.customers.find((x) => x.id === job.customerId)?.displayName ?? 'Customer', businessName: business.name })); const assignments = jobs.map((job) => ({ id: '1', assignmentType: 'TECHNICIAN' as const, professionalId: null, businessId: technician.businessId, technicianId: technician.id, technicianName: technician.displayName, assignedBy: business.ownerUserId, assignedAt: job.createdAt, unassignedAt: null, isActive: true })); return { ...technician, business: { id: business.id, name: business.name, city: business.city, province: business.province }, assignedJobCount: jobs.length, jobs, assignments }; }
  async listServiceCategories() { return this.categories; }
  async listServices(filters: AdminServiceFilters) { return page(this.services.filter((x) => (!filters.categoryId || x.categoryId === filters.categoryId) && (filters.isActive === null || x.isActive === filters.isActive) && textMatch([x.name, x.slug, x.categoryName], filters.search)), filters); }
  async getService(id: string) { return this.services.find((x) => x.id === id) ?? null; }
  async createService(input: ServiceMutationInput, actorId: string) { const category = this.categories.find((x) => x.id === input.categoryId); if (!category) throw new AdminStoreError('NOT_FOUND', 'Category not found.'); if (this.services.some((x) => x.slug === input.slug)) throw new AdminStoreError('CONFLICT', 'A service with this slug already exists.'); if (this.services.some((x) => x.categoryId === input.categoryId && x.name === input.name)) throw new AdminStoreError('CONFLICT', 'A service with this name already exists in the category.'); this.serviceSeq += 1; const timestamp = now(); const row: AdminServiceDto = { id: String(this.serviceSeq), categoryId: input.categoryId, categoryName: category.name, categorySlug: category.slug, name: input.name, slug: input.slug, description: input.description, isActive: input.isActive, sortOrder: input.sortOrder, createdAt: timestamp, updatedAt: timestamp }; this.services.push(row); try { this.writeAudit('SERVICE_CREATED', 'SERVICE', row.id, actorId); } catch (error) { this.services.pop(); throw error; } return row; }
  async updateService(id: string, input: Partial<ServiceMutationInput>, actorId: string) { const row = this.services.find((x) => x.id === id); if (!row) return null; const category = input.categoryId ? this.categories.find((x) => x.id === input.categoryId) : null; if (input.categoryId && !category) throw new AdminStoreError('NOT_FOUND', 'Category not found.'); const nextCategoryId = input.categoryId ?? row.categoryId; if (input.slug && this.services.some((x) => x.id !== id && x.slug === input.slug)) throw new AdminStoreError('CONFLICT', 'A service with this slug already exists.'); if (input.name && this.services.some((x) => x.id !== id && x.categoryId === nextCategoryId && x.name === input.name)) throw new AdminStoreError('CONFLICT', 'A service with this name already exists in the category.'); const previous = { ...row }; Object.assign(row, input, category ? { categoryName: category.name, categorySlug: category.slug } : {}, { updatedAt: now() }); try { this.writeAudit(input.isActive === false ? 'SERVICE_DEACTIVATED' : input.isActive === true && !previous.isActive ? 'SERVICE_ACTIVATED' : 'SERVICE_UPDATED', 'SERVICE', row.id, actorId); } catch (error) { Object.assign(row, previous); throw error; } return row; }
  async listJobs(filters: AdminJobFilters) { const rows = this.jobs.filter((x) => (!filters.source || x.source === filters.source) && (!filters.status || x.status === filters.status) && (!filters.customerId || x.customerId === filters.customerId) && (!filters.professionalId || x.professionalId === filters.professionalId) && (!filters.businessId || x.businessId === filters.businessId) && (!filters.from || x.createdAt >= startOfDay(filters.from)) && (!filters.to || x.createdAt <= endOfDay(filters.to)) && textMatch([x.reference, x.title, x.description], filters.search)); return page(rows, filters); }
  async getJob(id: string): Promise<AdminJobDetailDto | null> { const job = this.jobs.find((x) => x.id === id); if (!job) return null; const internal = job.source === 'INTERNAL'; const timeline = internal ? [{ previousStatus: null, status: 'REQUESTED', reason: 'Internal job created by business', createdAt: job.createdAt }, { previousStatus: 'REQUESTED', status: 'IN_PROGRESS', reason: 'Work started', createdAt: job.updatedAt }] : [{ previousStatus: null, status: 'REQUESTED', reason: 'Customer submitted request', createdAt: job.createdAt }]; const quotes = internal ? [] : [{ id: '1', professionalId: job.professionalId, businessId: null, providerName: this.providerName(job), total: job.agreedAmount ?? 0, currency: job.currency, message: 'Quote for requested work', status: job.status === 'REQUESTED' ? 'SUBMITTED' : 'ACCEPTED', submittedAt: job.createdAt, createdAt: job.createdAt, items: [{ id: '1', description: this.serviceName(job.serviceId), quantity: 1, unitPrice: job.agreedAmount ?? 0, total: job.agreedAmount ?? 0, sortOrder: 1 }] }]; const assignments = internal ? [{ id: '1', assignmentType: 'BUSINESS' as const, professionalId: null, businessId: job.businessId, technicianId: null, technicianName: null, assignedBy: null, assignedAt: job.createdAt, unassignedAt: null, isActive: true }, { id: '2', assignmentType: 'TECHNICIAN' as const, professionalId: null, businessId: job.businessId, technicianId: '1', technicianName: 'Lerato Maseko', assignedBy: '301', assignedAt: job.createdAt, unassignedAt: null, isActive: true }] : [{ id: '1', assignmentType: 'PROFESSIONAL' as const, professionalId: job.professionalId, businessId: null, technicianId: null, technicianName: null, assignedBy: null, assignedAt: job.createdAt, unassignedAt: null, isActive: true }]; const documentation = internal ? { images: [{ id: '1', uploadedBy: '303', phase: 'BEFORE', originalFilename: 'before.jpg', mimeType: 'image/jpeg', size: 1200, createdAt: job.createdAt }], updates: [{ id: '1', authorId: '303', phase: 'DURING', note: 'Checked the leak and isolated the supply.', createdAt: job.updatedAt }], voiceNotes: [{ id: '1', authorId: '303', originalFilename: 'update.webm', mimeType: 'audio/webm', size: 2400, durationSeconds: 12, createdAt: job.updatedAt }], partsRequests: [{ id: '1', requesterId: '303', status: 'APPROVED', reason: 'Replacement valve required', reviewNotes: 'Approved', reviewedAt: job.updatedAt, createdAt: job.createdAt, updatedAt: job.updatedAt, items: [{ id: '1', partName: 'Replacement valve', quantity: 1, notes: null, hasPhoto: false, createdAt: job.createdAt }] }] } : { images: [], updates: [], voiceNotes: [], partsRequests: [] }; return { ...job, timeline, quotes, assignments, documentation }; }
  async listVerifications(filters: AdminVerificationFilters) { return page(this.verifications.filter((x) => (!filters.type || x.type === filters.type) && (!filters.status || x.status === filters.status) && (!filters.userId || x.userId === filters.userId) && textMatch([x.userEmail], filters.search)), filters); }
  async getVerification(id: string) { return this.verifications.find((x) => x.id === id) ?? null; }
  async decideVerification(id: string, decision: 'APPROVED' | 'REJECTED' | 'NEEDS_INFO', input: VerificationDecisionInput, actorId: string) { const row = this.verifications.find((x) => x.id === id); if (!row) return null; if (row.type === 'CERTIFICATE') throw new AdminStoreError('CONFLICT', 'Certificate verification must use the certificate workflow.'); if (row.status === 'APPROVED' || row.status === 'REJECTED') throw new AdminStoreError('CONFLICT', 'Verification decision is already final.'); const previous = { ...row }; const identityPrevious = this.identity.get(row.id); const profile = row.type === 'IDENTITY' ? this.professionals.find((x) => x.userId === row.userId) : undefined; const business = row.type === 'BUSINESS' ? this.businesses.find((x) => x.ownerUserId === row.userId) : undefined; const profilePrevious = profile?.verificationStatus; const businessPrevious = business?.verificationStatus; const badge = decision === 'APPROVED' ? 'VERIFIED' : decision === 'REJECTED' ? 'REJECTED' : 'PENDING'; row.status = decision; row.reviewedBy = actorId; row.reviewedAt = now(); row.reviewNotes = input.notes; row.updatedAt = now(); if (row.type === 'IDENTITY') this.identity.set(row.id, decision); if (profile) profile.verificationStatus = badge; if (business) business.verificationStatus = badge; try { this.writeAudit(`VERIFICATION_${decision === 'APPROVED' ? 'APPROVED' : decision === 'REJECTED' ? 'REJECTED' : 'INFO_REQUESTED'}`, 'VERIFICATION_REQUEST', row.id, actorId); } catch (error) { Object.assign(row, previous); if (identityPrevious) this.identity.set(row.id, identityPrevious); if (profile && profilePrevious) profile.verificationStatus = profilePrevious; if (business && businessPrevious) business.verificationStatus = businessPrevious; throw error; } return row; }
  async listCertificates(filters: AdminCertificateFilters) { return page(this.certificates.filter((x) => (!filters.status || x.verificationStatus === filters.status) && (!filters.professionalId || x.professionalId === filters.professionalId) && (!filters.businessId || x.businessId === filters.businessId) && textMatch([x.title, x.issuingOrganisation], filters.search)), filters); }
  async getCertificate(id: string) { return this.certificates.find((x) => x.id === id) ?? null; }
  async decideCertificate(id: string, decision: 'APPROVED' | 'REJECTED' | 'NEEDS_INFO', input: CertificateDecisionInput, actorId: string) { const row = this.certificates.find((x) => x.id === id); if (!row) return null; if (row.verificationStatus === 'APPROVED' || row.verificationStatus === 'REJECTED') throw new AdminStoreError('CONFLICT', 'Certificate decision is already final.'); const previous = { ...row }; row.verificationStatus = decision; row.reviewedBy = actorId; row.reviewedAt = now(); row.reviewNotes = input.notes; row.updatedAt = now(); this.certificateHistory.set(id, [...(this.certificateHistory.get(id) ?? []), decision]); try { this.writeAudit(`CERTIFICATE_${decision === 'APPROVED' ? 'APPROVED' : decision === 'REJECTED' ? 'REJECTED' : 'INFO_REQUESTED'}`, 'CERTIFICATE', row.id, actorId); } catch (error) { Object.assign(row, previous); this.certificateHistory.set(id, (this.certificateHistory.get(id) ?? []).slice(0, -1)); throw error; } return row; }
  async listReviews(filters: AdminReviewFilters) { return page(this.reviews.filter((x) => (filters.rating === null || x.rating === filters.rating) && (filters.minRating === null || x.rating >= filters.minRating) && (filters.maxRating === null || x.rating <= filters.maxRating) && textMatch([x.comment, x.customerName, x.providerName], filters.search)), filters); }
  async getReview(id: string) { return this.reviews.find((x) => x.id === id) ?? null; }
  async listReports(filters: AdminReportFilters) { return page(this.reports.filter((x) => (!filters.type || x.reportType === filters.type) && (!filters.status || x.status === filters.status) && textMatch([x.reason, x.description], filters.search)), filters); }
  async getReport(id: string) { return this.reports.find((x) => x.id === id) ?? null; }
  async updateReportStatus(id: string, expectedStatus: ReportStatusInput['status'], input: ReportStatusInput, actorId: string) { const row = this.reports.find((x) => x.id === id); if (!row) return null; if (row.status !== expectedStatus) throw new AdminStoreError('CONFLICT', 'Report status changed.'); if (row.status === 'RESOLVED' || row.status === 'DISMISSED' || row.status === input.status) throw new AdminStoreError('CONFLICT', 'Report status transition is not allowed.'); if (row.status === 'IN_REVIEW' && input.status === 'OPEN') throw new AdminStoreError('CONFLICT', 'Invalid report status transition.'); const previous = { ...row }; row.status = input.status; row.resolvedBy = input.status === 'RESOLVED' || input.status === 'DISMISSED' ? actorId : null; row.resolvedAt = input.status === 'RESOLVED' || input.status === 'DISMISSED' ? now() : null; row.updatedAt = now(); try { this.writeAudit('REPORT_UPDATED', 'REPORT', row.id, actorId); } catch (error) { Object.assign(row, previous); throw error; } return row; }
  async listDisputes(filters: AdminDisputeFilters) { return page(this.disputes.filter((x) => (!filters.status || x.status === filters.status) && textMatch([x.reason, x.description, x.resolution], filters.search)), filters); }
  async getDispute(id: string) { return this.disputes.find((x) => x.id === id) ?? null; }
  async updateDispute(id: string, expectedStatus: DisputeUpdateInput['status'], input: DisputeUpdateInput, actorId: string) { const row = this.disputes.find((x) => x.id === id); if (!row) return null; if (row.status !== expectedStatus) throw new AdminStoreError('CONFLICT', 'Dispute status changed.'); if (row.status === 'CLOSED' || row.status === 'RESOLVED' || row.status === input.status) throw new AdminStoreError('CONFLICT', 'Dispute status transition is not allowed.'); if (row.status === 'IN_REVIEW' && input.status === 'OPEN') throw new AdminStoreError('CONFLICT', 'Invalid dispute status transition.'); const previous = { ...row }; row.status = input.status; row.resolution = input.resolution; row.resolvedBy = input.status === 'RESOLVED' || input.status === 'CLOSED' ? actorId : null; row.resolvedAt = input.status === 'RESOLVED' || input.status === 'CLOSED' ? now() : null; row.updatedAt = now(); try { this.writeAudit('DISPUTE_UPDATED', 'DISPUTE', row.id, actorId); } catch (error) { Object.assign(row, previous); throw error; } return row; }
  async listAuditLogs(filters: AdminAuditFilters) { return page(this.audits.filter((x) => (!filters.actorId || x.actorId === filters.actorId) && (!filters.action || x.action === filters.action) && (!filters.entityType || x.entityType === filters.entityType) && (!filters.entityId || x.entityId === filters.entityId) && (!filters.from || x.createdAt >= startOfDay(filters.from)) && (!filters.to || x.createdAt <= endOfDay(filters.to)) && textMatch([x.action, x.entityType, x.actorEmail], filters.search)), filters); }
  async getAuditLog(id: string) { return this.audits.find((x) => x.id === id) ?? null; }
  async appendAudit(action: string, entityType: string, entityId: string, actorId: string, metadata: Record<string, unknown> = {}) { this.audits.push({ id: String(this.auditSeq++), actorId, actorEmail: null, action, entityType, entityId, metadata, ipAddress: null, createdAt: now() }); }
}
